language: python
python:
  - 2.7

install:
  - pip install ansible

script:
  - ./ansible-exec localhost test/tasks.yml -- -c local
  - ./ansible-exec localhost test/role -- -c local
  - ./ansible-exec localhost test/playbook.yml -- -c local